inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/rake'
    - 'spec/dummy/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
