version: 2.1

orbs:
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - solidusio_extensions/run-tests
      - run:
          name: Install & Upload test coverage to Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter format-coverage -t simplecov -o ./coverage/codeclimate.json
            ./cc-test-reporter upload-coverage

  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - solidusio_extensions/run-tests
      - run:
          name: Check if Schema is up-to-date
          command: |
            mv schema.graphql old_schema.graphql
            bundle exec rake schema:idl
            diff old_schema.graphql schema.graphql

  verify-schema:
    docker:
      - image: circleci/ruby:2.5.0-node
    steps:
      - checkout
      - run:
          name: Install GraphQL::SchemaComparator
          command: gem install graphql-schema_comparator
      - run:
          name: Run Verify
          command: rm Gemfile && schema_comparator verify "`git show master:schema.graphql`" schema.graphql

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - verify-schema
      - run-specs-with-postgres
      - run-specs-with-mysql
